// <auto-generated />
using MVC_Battler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Battler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220801000307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_Battler.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Toughness")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Combatants");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Character");
                });

            modelBuilder.Entity("MVC_Battler.Models.Enemy", b =>
                {
                    b.HasBaseType("MVC_Battler.Models.Character");

                    b.HasDiscriminator().HasValue("Enemy");
                });

            modelBuilder.Entity("MVC_Battler.Models.Player", b =>
                {
                    b.HasBaseType("MVC_Battler.Models.Character");

                    b.HasDiscriminator().HasValue("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HP = 100,
                            Name = "Jerry",
                            Strength = 20,
                            Toughness = 10
                        },
                        new
                        {
                            Id = 2,
                            HP = 80,
                            Name = "Larry",
                            Strength = 40,
                            Toughness = 5
                        },
                        new
                        {
                            Id = 3,
                            HP = 120,
                            Name = "Gary",
                            Strength = 15,
                            Toughness = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
